### ISSUE TITLE
arkit dataset

### ISSUE THREAD

**Issue by zuixiaosanlang** [nianticlabs/simplerecon#10]
can you share a arkit dataset for simplerecon ??
i download from NeuralRecon , but donnot know how to use for simplerecon.
especially, configs/data/arkit_dense.yaml

thanks

**Comment by mohammed-amr** [comment]
Hello!

There is now a quick readme [data_scripts/IOS_LOGGER_ARKIT_README.md](https://github.com/nianticlabs/simplerecon/blob/main/data_scripts/IOS_LOGGER_ARKIT_README.md) for how to process and run inference an ios-logger scan using the script at data_scripts/ios_logger_preprocessing.py.
