### ISSUE TITLE
ScanNet extraction

### ISSUE THREAD

**Issue by fengziyue** [nianticlabs/simplerecon#12]
Hi:

Thank you so much for the amazing work!

Could you share the script for extracting all the `.sens` files to the resized depth and color files in the `sensor_data` folder? which will save lots of time for people who want to reproduce the training.

Thank you!

**Comment by mohammed-amr** [comment]
Sure! Added to TODOs.

**Comment by jeremyyx** [comment]
please, I want it too! :)

**Comment by mohammed-amr** [comment]
These are now at: https://github.com/nianticlabs/simplerecon/tree/main/data_scripts/scannet_wrangling_scripts
