### ISSUE TITLE
Request the file format for codebase arkit_dataset.py

### ISSUE THREAD

**Issue by zhoux121** [nianticlabs/simplerecon#17]
Hi,
Thanks for publishing this awesome work, great job! 
I am trying to use the Arkit scenes dataset with your amazing work. I found out that the Arkit scenes file format is different from the  ScanNetv2 Dataset, especially for the camera pose. 

The format for Arkit scenes(3dod):
ARKitScenes/threedod/sample_data/40753679/
├── 40753679_3dod_annotation.json
├── 40753679_3dod_mesh.ply
└── 40753679_frames
    ├── color.traj               # camera poses
    ├── color_intrinsics         # camera intrinsics
    │   ├── 6845.7061.pincam     # filenames are indexed by timestamps
    │   ├── 6845.8060.pincam
    │   ├── 6845.9060.pincam
    │   └── ...
    ├── depth_densified          # depth frames
    │   ├── 6845.80601079.png    # filenames are indexed by timestamps
    │   ├── 6845.90596450.png
    │   └── ...
    └── wide                     # color frames
        ├── 6845.70605696.png    # filenames are indexed by timestamps
        ├── 6845.80601079.png
        ├── 6845.90596450.png
        └── ...
color.traj format:
Column 1: timestamp
Columns 2-4: rotation (axis-angle representation in radians)
Columns 5-7: translation (in meters)

Could you please tell me what is the correct input format for arkit_dataset.py?

Thank you!

**Comment by mohammed-amr** [comment]
Sorry, the dataset name is a isnomer. This class file is meant to be used with scenes captures using the ios-logger capturing app and processed with NeuralRecon's processing scripts.

Sorry!
