### ISSUE TITLE
How to generate visualization?

### ISSUE THREAD

**Issue by kvuong2711** [nianticlabs/simplerecon#2]
Not related to the technical details of the paper, but very cool visualization, especially the video (Live Reconstruction). Can you share what tools you used to generate this kind of visualization? Thanks!

**Comment by mohammed-amr** [comment]
Hello! The code you're looking for is under `visualize_live_reconstruction.py` that calls on functions in `tools.mesh_renderer.py`. The smooth birdeseye camera logic is under [SmoothBirdseyeCamera](https://github.com/nianticlabs/simplerecon/blob/86b647ac7e6b3a27d935d905361f16c3b0031455/tools/mesh_renderer.py#L155) and the camera marker is at [camera_marker](https://github.com/nianticlabs/simplerecon/blob/86b647ac7e6b3a27d935d905361f16c3b0031455/tools/mesh_renderer.py#L265).

For depth visualization, see the generation scripts under https://github.com/nianticlabs/simplerecon/tree/main/visualization_scripts

Check https://github.com/nianticlabs/simplerecon#-visualization for how to use those scripts. 

Thanks!

**Comment by kvuong2711** [comment]
Thanks a lot for sharing!

**Comment by mohammed-amr** [comment]
Welcome!
