### ISSUE TITLE
 A question about source images

### ISSUE THREAD

**Issue by Jingjinganhao** [nianticlabs/simplerecon#23]
Hi @mohammed-amr :

Thank you for sharing . I want to run `test.py` only using one source  image. 

Which  parameters do I need to modify?

do I have to retrain the model?

**Comment by mohammed-amr** [comment]
Hey @Jingjinganhao,

The model is trained to predict depth from a cost volume built with seven source images.

You could try using the same model, but provide dummy data for source views (identity for pose and the same exact intrinsics as current view). Modify the code to pass this dummy data on the forward pass.

Ideally, you would train the model without source views by ignoring features from the cost volume. 

Good luck!
