### ISSUE TITLE
Question about Depth Intrinsics

### ISSUE THREAD

**Issue by huohuohuohuohuohuohuohuo** [nianticlabs/simplerecon#24]
Hi @mohammed-amr :

Thank you for sharing this amazing work, during reading your code, I have few questions about the depth intrinsics:

(1) What is the depth intrinsic loaded from sceneXXXX_XX/sceneXXXX_XX.txt used for? Except for the cost_volume building, does it have some other usages such as in fusion?

(2) The intrinsic for depth and color images looks different. Did SimpleRecon use the intrinsics for color image? If I only have color images and their intrinsics, can I use the color image intrinsics replace the depth intrinsics to reconstruct?

Any response will be greatly appreciated!

Sincerely,
Xiao Huo

**Comment by mohammed-amr** [comment]
Hello,

1. This is now fixed. It is unclear which set of intrinsics are in the sceneXXXX_XX/sceneXXXX_XX.txt, but after multiple people raised the issue we looked into it. The ones in the intrinsics folder seem to be more correct, as both depth and color intrinsics there are identical up to scale. The repo now uses those and new models have been uploaded.
2. Both depth and color intrinsics there are identical up to scale in ScanNet.
