### ISSUE TITLE
Using first but not last frame of a tuple as 'reference frame'?

### ISSUE THREAD

**Issue by fengziyue** [nianticlabs/simplerecon#29]
Hi @mohammed-amr : 

Thank you for sharing this amazing work!

During reading the codes, I noticed that from [here](https://github.com/nianticlabs/simplerecon/blob/7de5b451e340f9a11c7fd67bd0c42204d0b009a9/datasets/generic_mvs_dataset.py#L608) you are using the first frame instead of the last frame (stated in the paper) in each tuple as the reference frame. In this case, the model is actually using 'future frames' information for predicting the current frame depth. Is my understanding correct?

Any insights are greatly appreciated!

**Comment by fengziyue** [comment]
Seems in 'test_eight_view_deepvmvs' the first frame in the tuple is the last frame in actual time, but in 'train_eight_view_deepvmvs' and 'val_eight_view_deepvmvs,' the first frame is the first in actual time.

**Comment by mohammed-amr** [comment]
For default and dense test tuples, the first frame in the line is the reference frame. All following frames are source frames.

The sort you linked is on source frames only.

**Comment by mohammed-amr** [comment]
Train and val tuples use whatever combination of future and past source frames. This is fine. It's from DVMVS's tuple augmentation strategy. 

Please see the tuple generation scripts for more.
