### ISSUE TITLE
Evaluation on DTU and Tanks&Temples

### ISSUE THREAD

**Issue by eugenelyj** [nianticlabs/simplerecon#33]
Hi, i am curious that if the proposed method can work on popular benchmarks that are used in MVS, like DTU and Tanks&Temples?

**Comment by mohammed-amr** [comment]
SimpleRecon is for monocular depth estimation from posed video. We do show how metadata can help improve scores for a general MVS method, CasMVSNet, on DTU. See S8 in the supplemental of the paper.

**Comment by UsamaHasan** [comment]
@eugenelyj any luck evaluating it on the DTU dataset?

**Comment by eugenelyj** [comment]
@UsamaHasan No, i didn't try...

**Comment by UsamaHasan** [comment]
![snapshot01](https://user-images.githubusercontent.com/19313963/230029536-222ccbeb-e0e4-4292-b1e4-dddd76a1f878.png)
I did try but the results are pretty strange on tanks and temples, the same goes for DTU scans.

**Comment by CLinvx** [comment]
> ![snapshot01](https://user-images.githubusercontent.com/19313963/230029536-222ccbeb-e0e4-4292-b1e4-dddd76a1f878.png) I did try but the results are pretty strange on tanks and temples, the same goes for DTU scans.

Hi, have you save this problem? ^_^
