### ISSUE TITLE
missing generate_val_tuples.py file 

### ISSUE THREAD

**Issue by chenyifanj** [nianticlabs/simplerecon#36]
Hi, thanks for your great work!

The ./data_scripts/generate_val_tuples.py file is missing, can you upload this？

Thank you very much!!

**Comment by mohammed-amr** [comment]
Hello, please see this [part](https://github.com/nianticlabs/simplerecon#%EF%B8%8F%EF%B8%8F%EF%B8%8F-frame-tuples) of the README for how to generate val tuples. 

```
# train
python ./data_scripts/generate_train_tuples.py 
    --data_config configs/data/scannet_default_train.yaml
    --num_workers 16

# val
python ./data_scripts/generate_val_tuples.py 
    --data_config configs/data/scannet_default_val.yaml
    --num_workers 16
```
