### ISSUE TITLE
Predict Depth Image using multiple RGB images 

### ISSUE THREAD

**Issue by Xuefei98** [nianticlabs/simplerecon#37]
First of all! Great work! And thanks for open sourcing it!
We are trying to use SimpleRecon to reconstruct the depth image for each frame given a sequence of RGB images that collected by RealSenseD455. I wonder if there is an easy way to feed your custom images into the model? We do not necessary need the whole reconstruction part but the depth prediction. Thank you!

**Comment by mohammed-amr** [comment]
Hello, thanks!

SimpleRecon is in essence a depth predictor from a stream of posed RGB images. There are multiple examples of datasets for video streams in the repo. Please use those as a reference for writing your own dataset class that inherits from [GenericMVSDataset](https://github.com/nianticlabs/simplerecon/blob/dd1b3ac8fcad44aeefdadfdb30643831580c8c18/datasets/generic_mvs_dataset.py#L15).
