### ISSUE TITLE
set up environment

### ISSUE THREAD

**Issue by yzhou19** [nianticlabs/simplerecon#39]
Hi,

I just want to create environment firstly, however i got error after implementing "conda env create -f simplerecon_env.yml"

"
Pip subprocess error:
  error: subprocess-exited-with-error
  
  × Building wheel for scikit-image (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [608 lines of output]
      /tmp/pip-build-env-_z06x97j/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      Partial import of skimage during the build process.
      Compiling /tmp/pip-req-build-38a9x70y/skimage/morphology/_skeletonize_3d_cy.pyx because it changed.
      [1/1] Cythonizing /tmp/pip-req-build-38a9x70y/skimage/morphology/_skeletonize_3d_cy.pyx
      /tmp/pip-build-env-_z06x97j/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
ERROR: Could not build wheels for scikit-image, which is required to install pyproject.toml-based projects
\ 
failed
"

I tried to use pip install https://github.com/JamieWatson683/scikit-image/archive/single_mesh.zip, then I get the same error. I guess this is the error.
Thanks for your help.

**Comment by BenedictusKent** [comment]
Did you try ```pip install scikit-image```?

**Comment by yzhou19** [comment]
Hi, I tried before, but it did not work. However, I used newer pytorch version then it works now. Thanks

**Comment by mohammed-amr** [comment]
Glad it worked out. For future reference. Here's an env file with updated torch:

```
name: simplerecon
channels:
  - default
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - clang=15.0.7
  - llvm-openmp=15.0.7
  - python=3.9.7
  - pytorch=2.0.1
  - torchvision
  - pytorch-cuda=11.7
  - pytorch-lightning=1.5.4 # training utils
  - pillow # image op
  - tensorboard # logging
  - matplotlib # plotting
  - pip
  - pip:
    - kornia==0.6.7 # gradients
    - antialiased-cnns # anti aliased resnet
    - efficientnet_pytorch
    - timm # efficent
    - trimesh # mesh loading/storage, and mesh generation
    - transforms3d # for NeuralRecon's arkit
    - einops # batching one liners
    - moviepy # storing videos
    - pyrender # rendering meshes
    - open3d==0.14.1 # mesh fusion
    - scipy # transformations and a few others
    - protobuf<4.21.0 # lighting/tensorboard fix
    - setuptools==59.5.0 # fix for tensorboard
    - https://github.com/JamieWatson683/scikit-image/archive/single_mesh.zip # single mesh exporting for measure.marching_cubes
```

And do make sure you have g++ 8.3.0 installed: 
`g++ -v`
