### ISSUE TITLE
AssertionError: Tuple file doesn't exist! Pass none for mv_tuple_file_suffix if you don't actually need a tuple file, otherwise check your paths.

### ISSUE THREAD

**Issue by zhoux121** [nianticlabs/simplerecon#6]
Hi,
Thanks for open source your work, and the work is amazing.

I am trying to run your demo code, set the mv_tuple_file_suffix as None but still got assertion error. 

CUDA_VISIBLE_DEVICES=0 python test.py --name HERO_MODEL --output_base_path OUTPUT_PATH --config_file configs/models/hero_model.yaml --load_weights_from_checkpoint weights/hero_model.ckpt --data_config configs/data/vdr_dense.yaml --num_workers 8 --batch_size 1 --fast_cost_volume --run_fusion --depth_fuser open3d --fuse_color --dump_depth_visualization;

########################### Options ###########################

     random_seed: 0
     name: HERO_MODEL
     log_dir: /home/xiaoxin/tmp/tensorboard
     notes: 
     log_interval: 100
     val_interval: 1000
     val_batches: 100
     dataset: vdr
     dataset_path: /home/xiaoxin/projects/def-gigor/xiaoxin/simplerecon/mnt/res_nas/mohameds/vdr/
     num_workers: 8
     tuple_info_file_location: /home/xiaoxin/projects/def-gigor/xiaoxin/simplerecon/mnt/res_nas/mohameds/vdr/tuples/
     mv_tuple_file_suffix: None
     frame_tuple_type: dense
     model_num_views: 8
     num_images_in_tuple: 8
     dataset_scan_split_file: /home/xiaoxin/projects/def-gigor/xiaoxin/simplerecon/mnt/res_nas/mohameds/vdr/scans.txt
     split: test
     image_width: 512
     image_height: 384
     shuffle_tuple: False
     test_keyframe_buffer_size: 30
     lr: 0.0001
     wd: 0.0001
     num_sanity_val_steps: 0
     max_steps: 110000
     batch_size: 1
     val_batch_size: 16
     gpus: 2
     precision: 16
     lr_steps: [70000, 80000]
     resume: None
     load_weights_from_checkpoint: weights/hero_model.ckpt
     image_encoder_name: efficientnet
     depth_decoder_name: unet_pp
     loss_type: log_l1
     matching_encoder_type: resnet
     matching_feature_dims: 16
     matching_scale: 1
     matching_num_depth_bins: 64
     min_matching_depth: 0.25
     max_matching_depth: 5.0
     cv_encoder_type: multi_scale_encoder
     feature_volume_type: mlp_feature_volume
     output_base_path: OUTPUT_PATH
     run_fusion: True
     fuse_color: True
     fusion_max_depth: 3.0
     fusion_resolution: 0.04
     depth_fuser: open3d
     single_debug_scan_id: None
     skip_frames: None
     pc_fusion_z_thresh: 0.04
     n_consistent_thresh: 3
     voxel_downsample: 0.02
     mask_pred_depth: False
     cache_depths: False
     fusion_use_raw_lowest_cost: False
     high_res_validation: False
     fast_cost_volume: True
     standard_fps: 30
     dump_depth_visualization: True
     use_precomputed_partial_meshes: False
     viz_render_width: 640
     viz_render_height: 480
     cam_marker_size: 0.7
     back_face_alpha: 0.5

###############################################################

################################################################################
################################################################################

################################################################################
######################### Running fusion! Using open3d #########################
Output directory:
OUTPUT_PATH/HERO_MODEL/vdr/dense/meshes/0.04_3.0_open3d_color 
################################################################################

################################################################################
############################### Saving quick viz.###############################
#######Output directory:
OUTPUT_PATH/HERO_MODEL/vdr/dense/viz/quick_viz ########
################################################################################

INFO - 2022-09-16 12:08:38,701 - helpers - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-effv2-weights/tf_efficientnetv2_s_21ft1k-d7dafa41.pth)
################################################################################
########################## Using FeatureVolumeManager ##########################
 Number of source views:      7  
 Using all metadata.  
 Number of channels:          [202, 128, 128, 1]  
################################################################################

################################################################################
########################## Using FeatureVolumeManager ##########################
 Number of source views:      7  
 Using all metadata.  
 Number of channels:          [202, 128, 128, 1]  
################################################################################

################################################################################
######################## Using FastFeatureVolumeManager ########################
 Number of source views:      7  
 Using all metadata.  
 Number of channels:          [202, 128, 128, 1]  
################################################################################

  0%|                                                                                                             | 0/1168 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/project/6067317/xiaoxin/simplerecon/test.py", line 480, in <module>
    main(opts)
  File "/project/6067317/xiaoxin/simplerecon/test.py", line 229, in main
    dataset = dataset_class(
  File "/project/6067317/xiaoxin/simplerecon/datasets/vdr_dataset.py", line 53, in __init__
    super().__init__(dataset_path=dataset_path,
  File "/project/6067317/xiaoxin/simplerecon/datasets/generic_mvs_dataset.py", line 130, in __init__
    assert os.path.exists(tuple_information_filepath), ("Tuple file "
AssertionError: Tuple file doesn't exist! Pass none for mv_tuple_file_suffix if you don't actually need a tuple file, otherwise check your paths.

not sure which part I did wrong.

Thank you

**Comment by mohammed-amr** [comment]
Can you please share what your `vdr_dense.yaml` config file looks like? Looks like you may have a bad dataset path.

**Comment by zhoux121** [comment]
Hi,
The problem is solved, the datapath is incorrect. 
Thank you!

**Comment by HaFred** [comment]
Hi all, @zhoux121 @mohammed-amr , I was referring to [here](https://github.com/nianticlabs/simplerecon#-running-out-of-the-box) and I just have one question. Are the tuple files and data splits needed to be generated independently first before running the test.py? Seems like there are no these files provided under the vdr folder.
